#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to work with nginx

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
