#!/usr/bin/env bash
# This displays numbers from 1 to 20 and the values

i=1
while [ $i -lt 21 ]
do
	echo $i
	if [ $i = 4 ]
	then
		echo "bad luck from China"
	elif [ $i = 9 ]
	then
		echo "bad luck from Japan" 
	elif [ $i = 17 ]
	then
		echo "bad luck from Italy"
	fi
	(( i+=1 ))
done
