#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

# sudo systemctl reload gunicorn.service > /dev/null 2>
MASTER_PID=$(ps aux | grep 'gunicorn: master' | grep -v grep | awk '{print $2}')

# Send a signal to reload Gunicorn gracefully
kill -HUP $MASTER_PID >/dev/null 2>&1

# Wait for the master process to acknowledge the reload
while kill -0 $MASTER_PID >/dev/null 2>&1; do
    sleep 1
done

# Notify the master process that workers were renewed
kill -USR2 $MASTER_PID >/dev/null 2>&1
