#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

GUNICORN_PID=$(pgrep gunicorn)

# If Gunicorn is running, gracefully reload it
if [ -n "$GUNICORN_PID" ]; then
  echo "Reloading Gunicorn gracefully"
  kill -HUP "$GUNICORN_PID"
else
  echo "Gunicorn is not running"
fi
